// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prrvicdwprqlnnwlrymj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycnZpY2R3cHJxbG5ud2xyeW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTAwMTIsImV4cCI6MjA2ODI2NjAxMn0.o_2TAaJTbfNOYcWQTTLCdPwi_Gr_tq9P-v5-rfcQuYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});